# Copyright Reexpress AI, Inc. All rights reserved.
"""Refit a saved model's region ladder without training or matching."""

from __future__ import annotations

from collections.abc import Mapping
from datetime import datetime, timezone
import uuid

from .artifact import validate_artifact
from .calibration import NestedCalibrator
from .errors import CalibrationError
from .math import _validate_alpha_resolution
from .types import SDMArtifact


def recalibrate_artifact(artifact: SDMArtifact, *, alpha_resolution: float) -> SDMArtifact:
    """Return a new calibrated artifact using its saved calibration diagnostics.

    Only the alpha ladder is fitted. Weights, normalization, support, distance
    and rescaled-similarity CDFs, and saved diagnostics retain their values.
    Training history is preserved separately from recalibration provenance.
    The input artifact is not modified; use ``write_artifact`` to publish the
    result with fresh checksums at a new destination.
    """
    try:
        _validate_alpha_resolution(alpha_resolution)
    except ValueError as error:
        raise CalibrationError(str(error)) from error
    source = validate_artifact(artifact)
    if not source.calibration_rows:
        raise CalibrationError(
            "The model has no saved calibration diagnostics (calibration.jsonl). "
            "Use a model exported with the selected checkpoint's calibration records; "
            "the original calibration input is not a substitute after split shuffling."
        )
    rows = source.calibration_rows
    regions = NestedCalibrator(
        source.configuration["numberOfClasses"], float(alpha_resolution), source.configuration["oodLimit"]
    ).fit(
        [row["sdm"] for row in rows],
        [row["qPrime"] for row in rows],
        [row["label"] for row in rows],
        [row["prediction"] for row in rows],
    )
    # validate_artifact returns detached mappings, so updates cannot mutate the
    # source model or its training history. Payload hashes are regenerated by
    # write_artifact; their original JSON serialization may differ on export.
    manifest = source.manifest
    metadata = manifest.setdefault("metadata", {})
    previous = metadata.get("recalibration")
    recalibration = dict(previous) if isinstance(previous, Mapping) else {}
    recalibration.update(sourceModelID=source.model_id, source="savedCalibrationDiagnostics")
    metadata["recalibration"] = recalibration

    # Reexpress two reads this existing lineage convention when importing a model
    # to distinguish region recalibration from a new optimization run. The key
    # describes portable history; it does not claim the app produced this model.
    previous = metadata.get("workbenchRecalibration")
    lineage = dict(previous) if isinstance(previous, Mapping) else {}
    training_id = lineage.get("trainingModelID")
    training_date = lineage.get("trainingCreatedAt")
    lineage.update(
        sourceModelID=source.model_id,
        trainingModelID=training_id if isinstance(training_id, str) and training_id else source.model_id,
        trainingCreatedAt=training_date if isinstance(training_date, str) and training_date else manifest["createdAt"],
        previousAlphaResolution=source.configuration["alphaResolution"],
        calibrationCount=len(rows),
    )
    metadata["workbenchRecalibration"] = lineage
    manifest["configuration"]["alphaResolution"] = float(alpha_resolution)
    manifest["regions"] = [region.to_manifest_dict() for region in regions]
    manifest["modelID"] = str(uuid.uuid4())
    manifest["createdAt"] = datetime.now(timezone.utc).isoformat(timespec="seconds").replace("+00:00", "Z")
    from . import __version__
    manifest["producer"] = {"name": "reexpress_sdm", "version": __version__}
    manifest.pop("checksums", None)
    return validate_artifact(SDMArtifact(
        manifest, source.weights, source.support_vectors, source.support_records, rows
    ))
